apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "llm-training.fullname" . }}-config
  labels:
    {{- include "llm-training.labels" . | nindent 4 }}
data:
  training-config.json: |-
    {
      "model_path": "{{ .Values.trainingConfig.modelPath }}",
      "dataset_path": "{{ .Values.trainingConfig.datasetPath }}",
      "output_path": "{{ .Values.trainingConfig.outputPath }}",
      "training_args": {
        "learning_rate": {{ .Values.trainingConfig.trainingArgs.learningRate }},
        "batch_size": {{ .Values.trainingConfig.trainingArgs.batchSize }},
        "epochs": {{ .Values.trainingConfig.trainingArgs.epochs }},
        "gradient_accumulation_steps": {{ .Values.trainingConfig.trainingArgs.gradient_accumulation_steps }}
      }
    }