apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "llm-training.fullname" . }}
  labels:
    {{- include "llm-training.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "llm-training.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "llm-training.selectorLabels" . | nindent 8 }}
      annotations:
        prometheus.io/scrape: "{{ .Values.monitoring.enabled }}"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8080"
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - "/bin/bash"
            - "-c"
            - |
              python -m training.run \
                --model_path={{ .Values.trainingConfig.modelPath }} \
                --dataset_path={{ .Values.trainingConfig.datasetPath }} \
                --output_path={{ .Values.trainingConfig.outputPath }} \
                --learning_rate={{ .Values.trainingConfig.trainingArgs.learningRate }} \
                --batch_size={{ .Values.trainingConfig.trainingArgs.batchSize }} \
                --epochs={{ .Values.trainingConfig.trainingArgs.epochs }} \
                --gradient_accumulation_steps={{ .Values.trainingConfig.trainingArgs.gradient_accumulation_steps }}
          ports:
            - name: metrics
              containerPort: 8080
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: {{ .Values.persistence.mountPath }}
            - name: config
              mountPath: /etc/training/config
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        {{- if .Values.persistence.enabled }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "llm-training.fullname" . }}-data
        {{- end }}
        - name: config
          configMap:
            name: {{ include "llm-training.fullname" . }}-config