apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: { { include "llm-training.fullname" . } }
  labels: { { - include "llm-training.labels" . | nindent 4 } }
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: { { include "llm-training.fullname" . } }
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
