{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "llm-training.fullname" . }}
  labels:
    {{- include "llm-training.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "llm-training.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    {{- range .Values.networkPolicy.allowFromNamespaces }}
    - from:
        - namespaceSelector:
            matchLabels:
              name: {{ . }}
    {{- end }}
  egress:
    - {}
{{- end }}