apiVersion: v1
kind: Secret
metadata:
  name: {{ include "llm-training.fullname" . }}-secrets
  labels:
    {{- include "llm-training.labels" . | nindent 4 }}
type: Opaque
data:
  registry-credentials: {{ printf "{\"auths\":{\"%s\":{\"username\":\"changeme\",\"password\":\"changeme\"}}}" .Values.image.repository | b64enc }}