apiVersion: v1
kind: Service
metadata:
  name: { { include "llm-training.fullname" . } }
  labels: { { - include "llm-training.labels" . | nindent 4 } }
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector: { { - include "llm-training.selectorLabels" . | nindent 4 } }
